### ISSUE TITLE
phing test fails

### ISSUE THREAD

**Issue by piotrbaczek** [kohana/kohana#106]
Hi,
I get those errors on straight-out-of-the-box kohana 3.3/master:
`nzpetter@nzpetter-HP-ENVY:/var/www/html/kohana$ phing test
Buildfile: /var/www/html/kohana/build.xml

kohana > test:

PHPUnit 4.8.24 by Sebastian Bergmann and contributors.

.............................................................   61 / 1462 (  4%)
SSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSS  122 / 1462 (  8%)
SSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSS.................  183 / 1462 ( 12%)
.............................................................  244 / 1462 ( 16%)
.............................................................  305 / 1462 ( 20%)
.............................................................  366 / 1462 ( 25%)
.............................................................  427 / 1462 ( 29%)
.............................................................  488 / 1462 ( 33%)
...........SS................................................  549 / 1462 ( 37%)
.............................................................  610 / 1462 ( 41%)
.............................................................  671 / 1462 ( 45%)
.............................................................  732 / 1462 ( 50%)
.............................................................  793 / 1462 ( 54%)
.............................................................  854 / 1462 ( 58%)
.......................................................FFFF..  915 / 1462 ( 62%)
.............................................................  976 / 1462 ( 66%)
............................................................. 1037 / 1462 ( 70%)
............................................................. 1098 / 1462 ( 75%)
............................................................. 1159 / 1462 ( 79%)
.................FFFF........................................ 1220 / 1462 ( 83%)
............................................................. 1281 / 1462 ( 87%)
............FF.....FFFF...................................... 1342 / 1462 ( 91%)
............................................................. 1403 / 1462 ( 95%)
...........................................................

Time: 14,23 seconds, Memory: 28,00Mb

There were 14 failures:

1) Kohana_TextTest::test_bytes with data set #0 ('256.00 B', 256, null, null, true)
Failed asserting that two strings are identical.
--- Expected
+++ Actual
@@ @@
-256.00 B
+256,00 B

/var/www/html/kohana/system/tests/kohana/TextTest.php:401
/var/www/html/kohana/modules/unittest/classes/Kohana/Unittest/TestSuite.php:51

2) Kohana_TextTest::test_bytes with data set #1 ('1.02 kB', 1024, null, null, true)
Failed asserting that two strings are identical.
--- Expected
+++ Actual
@@ @@
-1.02 kB
+1,02 kB

/var/www/html/kohana/system/tests/kohana/TextTest.php:401
/var/www/html/kohana/modules/unittest/classes/Kohana/Unittest/TestSuite.php:51

3) Kohana_TextTest::test_bytes with data set #2 ('0.00147 GB', 1474560.0, 'GB', '%01.5f %s', true)
Failed asserting that two strings are identical.
--- Expected
+++ Actual
@@ @@
-0.00147 GB
+0,00147 GB

/var/www/html/kohana/system/tests/kohana/TextTest.php:401
/var/www/html/kohana/modules/unittest/classes/Kohana/Unittest/TestSuite.php:51

4) Kohana_TextTest::test_bytes with data set #3 ('1.00 MiB', 1048576, 'MiB', null, false)
Failed asserting that two strings are identical.
--- Expected
+++ Actual
@@ @@
-1.00 MiB
+1,00 MiB

/var/www/html/kohana/system/tests/kohana/TextTest.php:401
/var/www/html/kohana/modules/unittest/classes/Kohana/Unittest/TestSuite.php:51

5) Kohana_ValidTest::test_decimal with data set #4 ('45.1664', 4, null, true)
Decimal: "45.1664" to 4 places and  digits (preceeding period)
Failed asserting that false matches expected true.

/var/www/html/kohana/system/tests/kohana/ValidTest.php:217
/var/www/html/kohana/modules/unittest/classes/Kohana/Unittest/TestSuite.php:51

6) Kohana_ValidTest::test_decimal with data set #5 ('45.1664', 4, 2, true)
Decimal: "45.1664" to 4 places and 2 digits (preceeding period)
Failed asserting that false matches expected true.

/var/www/html/kohana/system/tests/kohana/ValidTest.php:217
/var/www/html/kohana/modules/unittest/classes/Kohana/Unittest/TestSuite.php:51

7) Kohana_ValidTest::test_decimal with data set #6 ('-45.1664', 4, null, true)
Decimal: "-45.1664" to 4 places and  digits (preceeding period)
Failed asserting that false matches expected true.

/var/www/html/kohana/system/tests/kohana/ValidTest.php:217
/var/www/html/kohana/modules/unittest/classes/Kohana/Unittest/TestSuite.php:51

8) Kohana_ValidTest::test_decimal with data set #7 ('+45.1664', 4, null, true)
Decimal: "+45.1664" to 4 places and  digits (preceeding period)
Failed asserting that false matches expected true.

/var/www/html/kohana/system/tests/kohana/ValidTest.php:217
/var/www/html/kohana/modules/unittest/classes/Kohana/Unittest/TestSuite.php:51

9) Kohana_ValidTest::test_numeric with data set #3 ('10.5', true)
Failed asserting that false matches expected true.

/var/www/html/kohana/system/tests/kohana/ValidTest.php:766
/var/www/html/kohana/modules/unittest/classes/Kohana/Unittest/TestSuite.php:51

10) Kohana_ValidTest::test_numeric with data set #4 ('-10.5', true)
Failed asserting that false matches expected true.

/var/www/html/kohana/system/tests/kohana/ValidTest.php:766
/var/www/html/kohana/modules/unittest/classes/Kohana/Unittest/TestSuite.php:51

11) Kohana_ValidTest::test_numeric with data set #10 ('.5', true)
Failed asserting that false matches expected true.

/var/www/html/kohana/system/tests/kohana/ValidTest.php:766
/var/www/html/kohana/modules/unittest/classes/Kohana/Unittest/TestSuite.php:51

12) Kohana_ValidTest::test_numeric with data set #11 ('-.5', true)
Failed asserting that false matches expected true.

/var/www/html/kohana/system/tests/kohana/ValidTest.php:766
/var/www/html/kohana/modules/unittest/classes/Kohana/Unittest/TestSuite.php:51

13) Kohana_ValidTest::test_numeric with data set #12 ('5.', true)
Failed asserting that false matches expected true.

/var/www/html/kohana/system/tests/kohana/ValidTest.php:766
/var/www/html/kohana/modules/unittest/classes/Kohana/Unittest/TestSuite.php:51

14) Kohana_ValidTest::test_numeric with data set #13 ('-5.', true)
Failed asserting that false matches expected true.

/var/www/html/kohana/system/tests/kohana/ValidTest.php:766
/var/www/html/kohana/modules/unittest/classes/Kohana/Unittest/TestSuite.php:51

FAILURES!
Tests: 1462, Assertions: 2973, Failures: 14, Skipped: 107.

BUILD FAILED
/var/www/html/kohana/build.xml:170:156: Task exited with code 1
Total time: 14.3280 seconds
`

Am i doing something wrong or am I missing php module?

**Comment by enov** [comment]
Thanks for reporting this @piotrgolasz.

Could you give me your environment info? OS, PHP version, and also the result of your `env` command might be helpful?

Yes, it might be you are missing modules (mbstring, PCRE with UTF-8). You can check the required modules by calling `install.php` from the browser.

**Comment by allyssum** [comment]
I use kohana bind php5.6.21 have a big bug, ORM find_all() conduct foreach(),obj not find _has_many objs, obj _has_many's _db_builder[args][id] is null,

**Comment by piotrbaczek** [comment]
Hey @enov ,

this is my env

> nzpetter@nzpetter-HP-ENVY:/var/www/html/kohana$ env
> XDG_VTNR=7
> LC_PAPER=sv_SE.UTF-8
> LC_ADDRESS=sv_SE.UTF-8
> XDG_SESSION_ID=c2
> XDG_GREETER_DATA_DIR=/var/lib/lightdm-data/nzpetter
> LC_MONETARY=sv_SE.UTF-8
> CLUTTER_IM_MODULE=xim
> SESSION=ubuntu
> GPG_AGENT_INFO=/home/nzpetter/.gnupg/S.gpg-agent:0:1
> TERM=xterm-256color
> VTE_VERSION=4205
> XDG_MENU_PREFIX=gnome-
> SHELL=/bin/bash
> QT_LINUX_ACCESSIBILITY_ALWAYS_ON=1
> WINDOWID=56638565
> LC_NUMERIC=sv_SE.UTF-8
> OLDPWD=/etc/php/7.0/cli
> UPSTART_SESSION=unix:abstract=/com/ubuntu/upstart-session/1000/2034
> GNOME_KEYRING_CONTROL=
> GTK_MODULES=gail:atk-bridge:unity-gtk-module
> USER=nzpetter
> LS_COLORS=rs=0:di=01;34:ln=01;36:mh=00:pi=40;33:so=01;35:do=01;35:bd=40;33;01:cd=40;33;01:or=40;31;01:mi=00:su=37;41:sg=30;43:ca=30;41:tw=30;42:ow=34;42:st=37;44:ex=01;32:_.tar=01;31:_.tgz=01;31:_.arc=01;31:_.arj=01;31:_.taz=01;31:_.lha=01;31:_.lz4=01;31:_.lzh=01;31:_.lzma=01;31:_.tlz=01;31:_.txz=01;31:_.tzo=01;31:_.t7z=01;31:_.zip=01;31:_.z=01;31:_.Z=01;31:_.dz=01;31:_.gz=01;31:_.lrz=01;31:_.lz=01;31:_.lzo=01;31:_.xz=01;31:_.bz2=01;31:_.bz=01;31:_.tbz=01;31:_.tbz2=01;31:_.tz=01;31:_.deb=01;31:_.rpm=01;31:_.jar=01;31:_.war=01;31:_.ear=01;31:_.sar=01;31:_.rar=01;31:_.alz=01;31:_.ace=01;31:_.zoo=01;31:_.cpio=01;31:_.7z=01;31:_.rz=01;31:_.cab=01;31:_.jpg=01;35:_.jpeg=01;35:_.gif=01;35:_.bmp=01;35:_.pbm=01;35:_.pgm=01;35:_.ppm=01;35:_.tga=01;35:_.xbm=01;35:_.xpm=01;35:_.tif=01;35:_.tiff=01;35:_.png=01;35:_.svg=01;35:_.svgz=01;35:_.mng=01;35:_.pcx=01;35:_.mov=01;35:_.mpg=01;35:_.mpeg=01;35:_.m2v=01;35:_.mkv=01;35:_.webm=01;35:_.ogm=01;35:_.mp4=01;35:_.m4v=01;35:_.mp4v=01;35:_.vob=01;35:_.qt=01;35:_.nuv=01;35:_.wmv=01;35:_.asf=01;35:_.rm=01;35:_.rmvb=01;35:_.flc=01;35:_.avi=01;35:_.fli=01;35:_.flv=01;35:_.gl=01;35:_.dl=01;35:_.xcf=01;35:_.xwd=01;35:_.yuv=01;35:_.cgm=01;35:_.emf=01;35:_.ogv=01;35:_.ogx=01;35:_.aac=00;36:_.au=00;36:_.flac=00;36:_.m4a=00;36:_.mid=00;36:_.midi=00;36:_.mka=00;36:_.mp3=00;36:_.mpc=00;36:_.ogg=00;36:_.ra=00;36:_.wav=00;36:_.oga=00;36:_.opus=00;36:_.spx=00;36:_.xspf=00;36:
> QT_ACCESSIBILITY=1
> LC_TELEPHONE=sv_SE.UTF-8
> XDG_SESSION_PATH=/org/freedesktop/DisplayManager/Session0
> XDG_SEAT_PATH=/org/freedesktop/DisplayManager/Seat0
> SSH_AUTH_SOCK=/run/user/1000/keyring/ssh
> SESSION_MANAGER=local/nzpetter-HP-ENVY:@/tmp/.ICE-unix/2256,unix/nzpetter-HP-ENVY:/tmp/.ICE-unix/2256
> DEFAULTS_PATH=/usr/share/gconf/ubuntu.default.path
> XDG_CONFIG_DIRS=/etc/xdg/xdg-ubuntu:/usr/share/upstart/xdg:/etc/xdg
> DESKTOP_SESSION=ubuntu
> PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin
> QT_IM_MODULE=ibus
> QT_QPA_PLATFORMTHEME=appmenu-qt5
> LC_IDENTIFICATION=sv_SE.UTF-8
> XDG_SESSION_TYPE=x11
> PWD=/var/www/html/kohana
> JOB=dbus
> XMODIFIERS=@im=ibus
> GNOME_KEYRING_PID=
> LANG=pl_PL.UTF-8
> GDM_LANG=pl
> MANDATORY_PATH=/usr/share/gconf/ubuntu.mandatory.path
> LC_MEASUREMENT=sv_SE.UTF-8
> COMPIZ_CONFIG_PROFILE=ubuntu
> IM_CONFIG_PHASE=1
> GDMSESSION=ubuntu
> SESSIONTYPE=gnome-session
> GTK2_MODULES=overlay-scrollbar
> SHLVL=1
> HOME=/home/nzpetter
> XDG_SEAT=seat0
> LANGUAGE=pl
> GNOME_DESKTOP_SESSION_ID=this-is-deprecated
> XDG_SESSION_DESKTOP=ubuntu
> LOGNAME=nzpetter
> DBUS_SESSION_BUS_ADDRESS=unix:abstract=/tmp/dbus-501U3nZdb2
> XDG_DATA_DIRS=/usr/share/ubuntu:/usr/share/gnome:/usr/local/share/:/usr/share/:/var/lib/snapd/desktop
> QT4_IM_MODULE=xim
> LESSOPEN=| /usr/bin/lesspipe %s
> INSTANCE=
> XDG_RUNTIME_DIR=/run/user/1000
> DISPLAY=:0
> XDG_CURRENT_DESKTOP=Unity
> GTK_IM_MODULE=ibus
> LESSCLOSE=/usr/bin/lesspipe %s %s
> LC_TIME=sv_SE.UTF-8
> LC_NAME=sv_SE.UTF-8
> XAUTHORITY=/home/nzpetter/.Xauthority
> _=/usr/bin/env

I'm running:

> nzpetter@nzpetter-HP-ENVY:/var/www/html/kohana$ lsb_release -a
> No LSB modules are available.
> Distributor ID: Ubuntu
> Description:    Ubuntu 16.04 LTS
> Release:    16.04
> Codename:   xenial

php version is:

> nzpetter@nzpetter-HP-ENVY:/var/www/html/kohana$ php -v
> PHP 7.0.6-13+donate.sury.org~xenial+1 (cli) ( NTS )
> Copyright (c) 1997-2016 The PHP Group
> Zend Engine v3.0.0, Copyright (c) 1998-2016 Zend Technologies
>     with Zend OPcache v7.0.6-dev, Copyright (c) 1999-2016, by Zend Technologies
>     with Xdebug v2.4.0, Copyright (c) 2002-2016, by Derick Rethans

these are my modules:

> nzpetter@nzpetter-HP-ENVY:/var/www/html/kohana$ php -m
> [PHP Modules]
> calendar
> Core
> ctype
> curl
> date
> dom
> exif
> fileinfo
> filter
> ftp
> gd
> gettext
> hash
> iconv
> json
> libxml
> mbstring
> mcrypt
> mysqli
> mysqlnd
> openssl
> pcntl
> pcre
> PDO
> pdo_mysql
> Phar
> posix
> propro
> raphf
> readline
> Reflection
> session
> shmop
> SimpleXML
> sockets
> SPL
> standard
> sysvmsg
> sysvsem
> sysvshm
> tokenizer
> wddx
> xdebug
> xml
> xmlreader
> xmlwriter
> xsl
> Zend OPcache
> zlib

[Zend Modules]
Xdebug
Zend OPcache

**Comment by piotrbaczek** [comment]
Hey @enov I can confirm, this goes through, however I still get a php notice

`PHP Notice:  Use of undefined constant CURLOPT_PROXYPORT - assumed 'CURLOPT_PROXYPORT' in /var/www/html/system/tests/kohana/RequestTest.php on line 488`

However, the test runs with success, therefore I close this task.

**Comment by enov** [comment]
Thanks @piotrgolasz, kindly open a new issue for the `PHP Notice` you're getting
