### ISSUE TITLE
Return api documentation to the website please

### ISSUE THREAD

**Issue by radiocity** [kohana/kohana#112]

**Comment by neo22s** [comment]
https://docs.koseven.ga/

**Comment by radiocity** [comment]
https://v2docs.kohanaframework.org/3.3/guide-api/

**Comment by neo22s** [comment]
https://docs.koseven.ga/guide-api

**Comment by sigma-technology** [comment]
Never before has an avatar been so apt.

**Comment by radiocity** [comment]
@neo22s, your version excludes orm and database modules

**Comment by neo22s** [comment]
@radiocity not my version actually its a copy of what was online... :S I will review https://github.com/koseven/koseven/issues/128

**Comment by radiocity** [comment]
Ty. Im not familiar with english.
