### ISSUE TITLE
Add additional validation to support // for HTML::styles and HTML::scripts

### ISSUE THREAD

**Issue by gianebao** [kohana/kohana#40]
The `HTML::styles` and `HTML::scripts` methods only check for the presence of `://`. We should also support the `//# sourceMappingURL` which are URLs that does not implicitly specify the protocol.

Here is an example:

http://jquery.com/download/#jquery-39-s-cdn-provided-by-maxcdn

**Comment by danielvalentin** [comment]
I agree. Pull request for a suggested fix: https://github.com/kohana/core/pull/532

**Comment by gianebao** [comment]
Thanks!

**Comment by enov** [comment]
This has been fixed in kohana/core#549. Thanks for reporting!
