### ISSUE TITLE
system/tests/kohana/CookieTest.php is always skipped

### ISSUE THREAD

**Issue by fredemmott** [kohana/kohana#47]
They skip if headers_sent(); in CLI mode, headers_sent() is true if there's been any output - this includes the 'PHPUnit 4.2.2 by Sebastian Bergmann.' line :)

**Comment by acoulton** [comment]
This is resolved by kohana/core@f6aee42 which is now available in the development version of kohana/core and in the 3.3/develop branch of kohana/kohana.

@fredemmott thanks for reporting this.
