### ISSUE TITLE
Setup travis directly on the modules and core

### ISSUE THREAD

**Issue by rjd22** [kohana/kohana#50]
I think that we should split off the travis checks into multiple checks for every module and core having their own tests.

We should start to aim at loose coupling. So for now the build files should pull in the needed libraries like kohana/core and the kohana/kohana setup. And run the tests.

The later aim is to make the modules self sufficient later on removing the dependencies to core and making them testable with little / without any dependencies.

What do you guys think? @shadowhand @enov @acoulton

**Comment by acoulton** [comment]
@rjd22 agreed - it's on my list. We have kohana/koharness largely ready to go, I just need to get a moment to get it all configured for the modules - and it's going to need a bit more work and thought to cope with the recent changes to the Kohana::modules / Kohana::init_modules stuff.

I still think there needs to be somewhere that we run the full suite, with the stock bootstrap, index.php, default configs, etc - to verify that kohana/kohana does actually work out of the box as it's supposed to. Obviously with tests running separately on each of the modules it should be much less likely that unrelated failures would break kohana/kohana.

That said, it's still not 100% straightforward - for eg the change to Kohana::modules involved a change in kohana/core and in the required bootstrap calls. I can update koharness to always pull in the latest bootstrap.php from kohana/kohana - but that could still mean the kohana/core tests wouldn't build till the bootstrap change was merged. The other way round kohana/kohana won't pass until the kohana/core change is merged. And as we just saw on #48 changes to the bootstrap can obviously fatal the whole build so it's not just a question of knowing we have to ignore a couple of specific failing tests - there could be any number of other failures hiding behind that.

I've been struggling to think of a good way to make sure that builds that genuinely do depend on changes across multiple modules can still show us a green PR before we merge them. 

Or do we just say that in those cases it's enough if the person merging (or submitting?) the related PRs has done a dry-run of all the merges locally and seen the full suite pass even though Travis won't be able to show that?

Any ideas would be welcome.

**Comment by enov** [comment]
> Or do we just say that in those cases it's enough if the person merging (or submitting?) the related PRs has done a dry-run of all the merges locally and seen the full suite pass even though Travis won't be able to show that?

You mean tracking latest submodule changes? I wonder if this git thing can help us to setup the submodules with the `-b` flag as seen here:

http://stackoverflow.com/a/9189815

I think this would help travis to update submodules the right way. Correct me if I am wrong.

**Comment by acoulton** [comment]
@enov we actually want to move to composer instead of submodules (per #41) which will solve the issue of making sure travis is up to date with the latest (eg) 3.4/develop without needing submodule update commits.

I'm talking about when there's a breaking change that relies on:
- changes to the bootstrap in kohana/kohana 3.4/feat/some-breaking-change
- changes to the core in kohana/core 3.4/feat/some-breaking-change
- changes to some other modules

So when travis builds the PR on kohana/core it needs the bootstrap from the feature branch in kohana/kohana. And when it builds the PR on kohana/kohana it needs the feature branch of kohana/core.

I can't figure out how to do that easily - changing the submodules or composer.json in those feature branches will cause merge conflicts.

I can't even decide if we actually want the build to be green in that case. Is it better for Travis to tell us it will pass when all the related feature branches get merged? Or is it better for Travis to warn us that the change will break unless we find all the dependencies and merge them too?

**Comment by rjd22** [comment]
What we can do is to build the whole kohana suite when someone does a pull request on a module for now and run the tests.

Later on we should try to decouple the modules in a way that they won't affect the core and the core won't affect them.

**Comment by enov** [comment]
> we actually want to move to composer instead of submodules

Yes. But maybe submodules tracking the tip of the branches are good for `3.3`?

> I can't even decide if we actually want the build to be green in that case.

In the case of a breaking change that affects several modules, I think it is OK for Travis to warn us. The author of that change will know that changes should be merges first in other projects. It seems that there is a way to tell Travis to run again (Restart Build) button, and that could be helpful.

**Comment by acoulton** [comment]
@rjd22 not a fan of that idea. Downsides are:
- We'd either have to add all the modules as composer dependencies of each other (which would cause runtime dependency issues for downstream users), or add some custom script to get all the other core modules for every build. Many more places to maintain version constraints, module list, etc.
- If someone breaks one module, all the PRs on all other modules will fail until that module is fixed. Much more noise and just takes us back to people merging PRs that are failing assuming that the issues are coming from somewhere else.
- Builds for each module will be much slower than they need to be

I'd much prefer that the module PRs only run the tests relevant to that module, and kohana/kohana runs the full suite. If we get a case where modules are green and kohana/kohana is red that will make it much easier to spot and fix unexpected dependencies/conflicts between modules.

**Comment by acoulton** [comment]
@enov 

> > we actually want to move to composer instead of submodules
> > Yes. But maybe submodules tracking the tip of the branches are good for 3.3?

Why? It just complicates the build setup to have two different approaches. Plus it requires someone to be maintaining those submodule references - which hasn't been happening.

> In the case of a breaking change that affects several modules, I think it is OK for Travis to warn us.

Yes, after describing the issue here I think I agree. The PRs themselves are likely to always stay red, but once they're all merged we should then see green builds on develop branches which is probably enough.

**Comment by rjd22** [comment]
@acoulton What I meant with my idea is at least a temporary solution for now that we can improve later. 
- For testing submodules we only need to include kohana/kohana and kohana/core in the build and only run the submodule tests.
- For testing the core we only need kohana/kohana in the build and only run the core tests.

After we can test them alone we should do so but that won't be doable now.

**Comment by acoulton** [comment]
@rjd22 ah, ok then I think we're talking about doing the same thing except that I plan to use kohana/koharness - which fakes up a kohana/kohana-style application but only using the relevant modules (the ones already defined in the module's composer.json).

It's basically done, just needs to be updated to handle the recent changes in 3.4 bootstrap and then added to the modules. I plan to do it when I get back from holiday week after next.

**Comment by acoulton** [comment]
This is now essentially complete for the 3.3 and 3.4 branches of all the modules - just waiting on review and merge on the related pull requests. Sorry it took a little longer than hoped to get back to this.
