### ISSUE TITLE
Cookie::$salt position disallows to use Auth cookies based in modules init.php

### ISSUE THREAD

**Issue by jfuentesa** [kohana/kohana#71]
If Cookie::$salt is moved before Kohana::modules() in bootstrap.php you can use Auth cookie based in your modules init.php

**Comment by enov** [comment]
@jfuentesa, `Cookie` can not be moved before `Kohana::modules()`, as it can not be extended anymore. Furthermore, authentication should not be made in `init.php` of your modules, as your application is not yet initialized in full. A suggestion might be to have a base controller for your restricted areas, and to move code related to `Auth` to that controller's `before` method.

**Comment by jfuentesa** [comment]
Then, I would to redirect to the dashboard (dashboard controller...) from the landingpage if the user is logged. Thank you for your help.

**Comment by enov** [comment]
You're welcome!
