### ISSUE TITLE
Missing link in lastest releases 3.3.4?

### ISSUE THREAD

**Issue by Daijobou** [kohana/kohana#76]
https://github.com/kohana/kohana/releases
~~
This release is not a drop-in replacement of v3.3.3.1. It contains a security fix discovered by HP Fortify. Please consult the Upgrading from v3.3.3.1 page in the manual.
~~
Where I can find this "Upgrading from v3.3.3.1 page" in the manual?
https://kohanaframework.org/3.3/guide/kohana/upgrading is only for upgrading from 3.2.

Thanks. :)

**Comment by enov** [comment]
Thanks @Daijobou, made https://github.com/kohana/kohanaframework.org/pull/30 that should update the official site's guide once merged.

**Comment by enov** [comment]
This was all set and here's the upgrade page:

https://kohanaframework.org/3.3/guide/kohana/upgrading-from-3-3-3-1

Cheers!
