### ISSUE TITLE
Tracker link in CONTRIBUTING.md is down

### ISSUE THREAD

**Issue by raelgc** [kohana/kohana#81]
In [`CONTRIBUTING.md`](https://github.com/kohana/kohana/blob/3.3/master/CONTRIBUTING.md) we can read:

> <h1><a id="user-content-contributing-to-the-project" class="anchor" href="#contributing-to-the-project" aria-hidden="true"><span class="octicon octicon-link"></span></a>Contributing to the project</h1>
> 
> 
> <p>All features and bugfixes must be fully tested and reference an issue in the <a href="http://dev.kohanaframework.org/projects/kohana3">tracker</a>, <strong>there are absolutely no exceptions</strong>.</p>

The `tracker` link is pointing to http://dev.kohanaframework.org/projects/kohana3, which is raising `Website is down` page, like below screenshot:

![kohana_521](https://cloud.githubusercontent.com/assets/263302/10364492/3c5f5686-6d92-11e5-9dcd-d08edd9245e9.png)

Not sure if the link is broken or the tracker is down.

**Comment by enov** [comment]
Thanks @raelgc.

Yes, http://dev.kohanaframework.org/projects/kohana3 used to be Kohana's issue tracker (Redmine). We're tracking issues now on Github.

The text needs to be fixed and rephrased.

**Comment by raelgc** [comment]
@enov, thanks for the fast answer.

Will a replace to `https://github.com/kohana/kohana/issues` be enough?

**Comment by enov** [comment]
Yeah, I guess that will be enough for the time being.

If you're willing to PR, please do so to the `3.3/develop` branch.

**Comment by rjd22** [comment]
Closing this since it is merged

**Comment by raelgc** [comment]
Should I replicate this fix for any 3.4 branch?

**Comment by enov** [comment]
No, there's no need. We occasionally merge changes up.
Thanks :)
