### ISSUE TITLE
memcache has bug?

### ISSUE THREAD

**Issue by iaping** [kohana/kohana#83]
kohana v3.3.4,memcached 1.4.4.
modules/cache/classes/Kohana/Cache/Memcache.php:

```
public function set($id, $data, $lifetime = 3600)
    {
        // If the lifetime is greater than the ceiling
        if ($lifetime > Cache_Memcache::CACHE_CEILING)
        {
            // Set the lifetime to maximum cache time
            $lifetime = Cache_Memcache::CACHE_CEILING + time();
        }
        // Else if the lifetime is greater than zero
        elseif ($lifetime > 0)
        {
            $lifetime += time();
        }
        // Else
        else
        {
            // Normalise the lifetime
            $lifetime = 0;
        }

        // Set the data to memcache
        return $this->_memcache->set($this->_sanitize_id($id), $data, $this->_flags, $lifetime);
    }
```

$lifetime is a long time,get values is null,why +time()?bug?

**Comment by enov** [comment]
We are adding the current timestamp (`time()`) to lifetime.

http://php.net/manual/en/memcache.set.php

> **expire**
> Expiration time of the item. If it's equal to zero, the item will never expire. You can also use Unix timestamp or a number of seconds starting from current time, but in the latter case the number of seconds may not exceed 2592000 (30 days).

If you still think there is a bug, kindly open a new issue in https://github.com/kohana/cache.

Thanks :)
