### ISSUE TITLE
Request->uri() bug

### ISSUE THREAD

**Issue by sergiozia** [kohana/kohana#94]
Hi,

When used as a getter, this method returns this :  return empty($this->_uri) ? '/' : $this->_uri;
But if $this->_uri equals '0', empty($this->_uri) returns true and '/' is returned instead of '0'

Example :  $request->uri() returns '/' far a request to http://www.mydomain.com/0

**Comment by sergiozia** [comment]
this patch runs correctly :
return ($this->_uri !== '' ? $this->_uri : '/');

**Comment by acoulton** [comment]
@sergiozia thanks for reporting that, I've submitted a fix in kohana/core#664
